remote_theme: "mmistakes/minimal-mistakes@4.24.0"
title: ""
name: "2Terezky"
description: "Our Wedding Celebration"

# Build settings
plugins:
  - jekyll-feed
  - jekyll-include-cache
  - jekyll-sitemap
  - jekyll-paginate

# Theme settings
defaults:
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: false
      header:
        overlay_color: "#000"
        overlay_filter: "0.5"
      sidebar:
        nav: "side"

# Site settings
locale: "sk-SK"
minimal_mistakes_skin: "default"
search: false

theme: minimal-mistakes-jekyll